///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class FaqModel {
/*
{
  "id": 1,
  "question": "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
  "answer": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia,\nmolestiae quas vel sint commodi repudiandae consequuntur voluptatum laborum\nnumquam blanditiis harum quisquam eius sed odit fugiat iusto fuga praesentium\noptio, eaque rerum! Provident similique accusantium nemo autem."
} 
*/

  int? id;
  String? question;
  String? answer;

  FaqModel({
    this.id,
    this.question,
    this.answer,
  });
  FaqModel.fromJson(Map<String, dynamic> json) {
    id = int.tryParse(json['id']?.toString() ?? '');
    question = json['question']?.toString();
    answer = json['answer']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['question'] = question;
    data['answer'] = answer;
    return data;
  }

  @override
  String toString() {
    return 'FaqModel{id: $id, question: $question, answer: $answer}';
  }
}
